### ISSUE TITLE
InMemory and Redis project version

### ISSUE THREAD

**Issue by oicguy** [Iamcerba/AspNetCore.CacheOutput#12]
Unfortunately, I didn't see anyway to update those projects so the they would reference the newest version of CacheOutput. If you tell me how to do it, I'll put in another PR.

I know it's trivial, but it makes updating packages easier when I don't have to manually keep to packages in sync.

**Comment by Iamcerba** [comment]
Hi @oicguy,

Please check for updated versions in NuGet.

**Comment by oicguy** [comment]
Thanks!
