### ISSUE TITLE
Issue with InvalidateCache on pagination

### ISSUE THREAD

**Issue by hflexgrig** [Iamcerba/AspNetCore.CacheOutput#16]
There's issue with invalidate cache when we have pagination e.g.  we have httpget method 

[CacheOutput.....]
[HttpGet]
public IList<Result> Get([FromQuery] QueryObject query){
.....
...
}

class QueryObject{
int page,
.......
}

And we have invalidate cache on Post put delete requests. A problem is that when we go through pages one time, after they're getting cached, and once we call invalidatecache , it invalidates only latest request (latest page), but we need to invalidate it for all pages. I went through the code and found the issue, will make pull request soon with the fix.

**Comment by Iamcerba** [comment]
Hey, @hflexgrig

I was able to reproduce the issue but seems like your PR doesn't resolve it.

**Comment by Iamcerba** [comment]
See the latest commit and let me know if it helped.

**Comment by hflexgrig** [comment]
Hi @Iamcerba  , Actually my changes and your changes almost identical and my changes works, I ended up with implementing my custom IApiCacheOutput with my fix, I've tested it and it works exactly as we expect. But most probably I'll go with your changes once it is published.

Thanks

**Comment by hflexgrig** [comment]
On your approach is just duplicate code was added, literally you have same 

`if (Cache.TryGetValue($"{dependsOnKey}{CancellationTokenKey}", out CancellationTokenSource existingCts))
                {
                    options.AddExpirationToken(new CancellationChangeToken(existingCts.Token));

                    Cache.Set(key, value, options);
                }`

inside if (string.IsNullOrEmpty(dependsOnKey)) and it's else condition, so what I have is just 

 if (string.IsNullOrEmpty(dependsOnKey) && !Cache.TryGetValue($"{dependsOnKey}{CancellationTokenKey}", out _))

**Comment by Iamcerba** [comment]
I've checked twice, your version is not working. It invalidates the cache only for the latest cached page that is pretty the same behavior as it was before the fix.

Don't you see the difference between:

```csharp
Cache.TryGetValue($"{dependsOnKey}{CancellationTokenKey}", out _)
```
and
```csharp
Cache.TryGetValue($"{key}{CancellationTokenKey}", out CancellationTokenSource existingCts)
```
?

**Comment by hflexgrig** [comment]
@Iamcerba  OMG I've made an mistake, actually I have two times cloned the repository, on the one I've tested there I used 
correct one , then on another I made pull request copied wrong one (. Ok you're right.

**Comment by hflexgrig** [comment]
Yeah, this is what I have in working example

```
public async Task AddAsync(string key, object value, DateTimeOffset expiration, string dependsOnKey = null)
        {
            var options = new MemoryCacheEntryOptions()
                .SetAbsoluteExpiration(expiration.Subtract(DateTimeOffset.Now));

            if (string.IsNullOrEmpty(dependsOnKey) && !Cache.TryGetValue($"{key}{CancellationTokenKey}", out _))
            {
                var cts = new CancellationTokenSource();

                options.AddExpirationToken(new CancellationChangeToken(cts.Token));

                Cache.Set(key, value, options);

                Cache.Set($"{key}{CancellationTokenKey}", cts, options);
            }
            else
            {
                if (Cache.TryGetValue($"{dependsOnKey}{CancellationTokenKey}", out CancellationTokenSource existingCts))
                {
                    options.AddExpirationToken(new CancellationChangeToken(existingCts.Token));

                    Cache.Set(key, value, options);
                }
            }
        }
```
