### ISSUE TITLE
Response Headers Readonly

### ISSUE THREAD

**Issue by sunnyonline** [Iamcerba/AspNetCore.CacheOutput#2]
I have added your project to my asp.net core 2 web app in VS2017. The line response.Headers[HeaderNames.ETag] = @"""" + etag.Replace("\"", string.Empty) + @"""";

in SetEtag(HttpResponse response, string etag) fails. Presumably because the Headers collection is readonly at this point. Any ideas?

Rob

**Comment by Iamcerba** [comment]
Hi @sunnyonline,

Did you add "app.UseCacheOutput();" in Startup.Configure(IApplicationBuilder app, IHostingEnvironment env) method? I mentioned this in configuration instructions.

**Comment by sunnyonline** [comment]
Perfect! Did the job. Thank you.

**Comment by sunnyonline** [comment]
Hi Alexander

I now have CacheOutput working as expected however app.UseCacheOutput() in
Startup.Configuration prevents exception pages from being shown, eg.
UseDeveloperExceptionPage() shows nothing. When app.UseCacheOutput() is
removed from startup the exception page shows.

Any ideas?

Regards,

Rob

**Comment by Iamcerba** [comment]
Hi @sunnyonline,
Try to reorder app.UseCacheOutput() and app.UseDeveloperExceptionPage() and always use  app.UseCacheOutput() as first registered middleware. Hope it will help.
