### ISSUE TITLE
Conditionally disable caching

### ISSUE THREAD

**Issue by toburger** [Iamcerba/AspNetCore.CacheOutput#26]
The old behavior was that the caching needed to be explicitly activated by providing the `UseCacheOutput` method.
Now the caching is implicitly active. It would be nice to activate the caching conditionally. For example I could activate the caching only for the production environment:

```cs
if (env.IsProduction())
{
    app.UseCacheOutput();
}
```

Is there a way to deactivate the caching? The only way I can think of is by implementing my own fake `IApiCacheOutput` which doesn't cache anything.

**Comment by Iamcerba** [comment]
There are a lot of ways to implement:
1. Preprocessor directives (conditional compilation) in every place where CacheOutput attribute is being used (not really convenient as for me).
2. Create your own attribute, inherited from existing CacheOutputAttribute, and override IsCachingAllowed method to always return false on condition.
3. Your option.
