### ISSUE TITLE
not support AutoInvalidateCacheOutput?

### ISSUE THREAD

**Issue by li-zheng-hao** [Iamcerba/AspNetCore.CacheOutput#29]

**Comment by li-zheng-hao** [comment]
in `Strathweb.CacheOutput`， it support three ways to invalidate cache:

- [AutoInvalidateCacheOutput] - on the controller level (through an attribute)
- [InvalidateCacheOutput("ActionName")] - on the action level (through an attribute)
- Manually - inside the action body

this version only support action level invalidation?

**Comment by Iamcerba** [comment]
It supports cache invalidation via attribute on controller action and also cache could be invalidated manually by injecting IApiCacheOutput. It is up to you to implement other options which are less useful on my opinion.

**Comment by li-zheng-hao** [comment]
Can I make any put post delete method in the controller automatically invalidate the cache of the get method（Usage of AutoInvalidateCacheOutput）？or i need to add InvalidateCacheOutput attribute in each put/post/delete method manually?

**Comment by li-zheng-hao** [comment]
and if there is many get method in controller , i need add many InvalidateCacheOutput(nameof("ActionName")) attribute in each put/post/delete method , this can cause great inconvenience

**Comment by li-zheng-hao** [comment]
If there is a solution to the problem I'm asking, can you please give some sample code ?

**Comment by li-zheng-hao** [comment]
ok, I solved this  problem  by setting method name as `*`
