### ISSUE TITLE
Is there possibility to vary cache by user groups?

### ISSUE THREAD

**Issue by Dmitrij-Polyanin** [Iamcerba/AspNetCore.CacheOutput#3]
Is there possibility to vary cache by user groups, or by some other custom logic?
I think i can do it using custom key provider, but I have a question.

I want to cache on "registered" and "unregistred" user groups, but not on "admin" or "moderator", because they have little % of traffic.

How can I check what to cache what to not vary by context?

**Comment by Dmitrij-Polyanin** [comment]
Hm. I think it can be done by custom key provider?

**Comment by Iamcerba** [comment]
Hey @Dmitrij-Polyanin,

I think the easiest way you can archive this is to write custom ICacheKeyGenerator which will generate empty cache key in case of the required user group and then implement custom IApiOutputCache with ContainsAsync method which will check if provided key is empty and return false. This way endpoint will always return uncached result for the desired user group.

**Comment by Dmitrij-Polyanin** [comment]
@Iamcerba Oh. Cool. Thanks for your help.

**Comment by Dmitrij-Polyanin** [comment]
Trying to make this. All normal, but there is one moment.

I wrote my own cache generator using user groups. I can register it globally, but i only want to work it on my custom `GroupCacheAttribute : CacheOutputAttribute`.

Is there an option to set `CacheGenerator` manually for any attribute instance. [Here ](https://github.com/Iamcerba/AspNetCore.CacheOutput/blob/37341c51bfad13b0b9b88ca2cb8d7c1bcef81029/AspNetCore.CacheOutput/CacheOutputAttribute.cs#L108)geting only default.

What is the best strategy to use my own?

I can override and copy all code from `OnActionExecutionAsync` and `OnResultExecutionAsync`, but this is not good...

**Comment by Iamcerba** [comment]
@Dmitrij-Polyanin, yes, it will be good option to support custom key generator per each CacheOutputAttribute. Moreover, it was originally supported in package which I migrated to ASP.NET Core and seems I missed this. Will look into this tomorrow and try to restore this possibility.

**Comment by Iamcerba** [comment]
@Dmitrij-Polyanin, I've added such possibility, check InMemory demo. 

In short: DefaultCacheKeyGenerator will be used unless you specify custom generator:

```csharp
[CacheOutput(..., CacheKeyGenerator = typeof(CustomCacheKeyGenerator))] 
```

Don't forget to register custom generator in your IoC: 
```csharp
services.AddSingleton<<CustomCacheKeyGenerator>>(); // Use type explicitly during registration
```

Also, I've added the possibility to override the logic of resolving custom cache key generator in CacheOutputAttribute.

Please let me know if something wrong.

**Comment by Dmitrij-Polyanin** [comment]
Oh. Cool! You are great!

**Comment by Dmitrij-Polyanin** [comment]
I am not sure is it good in all cases, but mabe to make in any custom CacheOutputAttribute possibility to manually generate keys without any KeyGenerator. To make ovveride function GenerateKey. And by defaul it will proxy KeyGenerator. Not to write custom generators if not needed.

Its only idia, not sure that need, but thinking.

**Comment by Iamcerba** [comment]
@Dmitrij-Polyanin, We also should take into consideration that CacheKeyGenerator is being used for cache invalidation.
