### ISSUE TITLE
Cache does not expire as given

### ISSUE THREAD

**Issue by dimuthun** [Iamcerba/AspNetCore.CacheOutput#4]
Even in the demo app, Servicer Side Cache does not expire even I set the duration to a smaller span like 10 seconds.  Debug into the code showed that in CheckForExpiredTime method in  Microsoft.Extensions.Caching.Memory returns false due to _absoluteExpiration or _slidingExpiration being null.

        private bool CheckForExpiredTime(DateTimeOffset now)
        {
            if (_absoluteExpiration.HasValue && _absoluteExpiration.Value <= now)
            {
                SetExpired(EvictionReason.Expired);
                return true;
            }

            if (_slidingExpiration.HasValue
                && (now - LastAccessed) >= _slidingExpiration)
            {
                SetExpired(EvictionReason.Expired);
                return true;
            }

            return false;
        }

**Comment by Iamcerba** [comment]
@dimuthun, try to download updated version 1.0.5.1 of the AspNetCore.CacheOutput.InMemory package and let me know if anything wrong.

**Comment by dimuthun** [comment]
I checked and it works as expected. Thanks!
