### ISSUE TITLE
File response cache issue

### ISSUE THREAD

**Issue by dimuthun** [Iamcerba/AspNetCore.CacheOutput#6]
I am returning an image file as the response of one of my endpoints. The image is stored in the database as a base64 string and returned as a file from the API.  The cached response does not return the file as a proper image file. Browser identifies it as a document instead of an image.

Controller method:

```
        [HttpGet("api/logo")]
        [CacheOutput(ServerTimeSpan = 300)]
        public IActionResult GetLogo(string clientCode, [FromQuery]string info)
        {
            string data = "iVBORw0KGgo---------Base 64 image data-------------AAAAElFTkSuQmCC";
            return File(Convert.FromBase64String(data), "image/png");
        }
```

![image](https://user-images.githubusercontent.com/1101020/53730134-0a978300-3e9d-11e9-9d2a-78e5346e0f53.png)

**Comment by Iamcerba** [comment]
@dimuthun, thanks for opening the issue.
I have tried to fix an issue and released a new version of the package. Please check.

**Comment by dimuthun** [comment]
Thanks for the quick response. The new version 1.0.10 has fixed the issue.
